(require "helix/configuration.scm")
(require (prefix-in helix. "helix/commands.scm"))

(define-lsp "steel-language-server" (command "steel-language-server") (args '()))
(define-language "scheme"
                 (language-servers '("steel-language-server")))

;; >>> helix-steel-plugins
;; generated by install-plugins.sh
;; selected: notify oil glyph forest term watcher streal recentf
(require "notify/notify.scm")

(require "oil/oil.scm")
(oil-configure! #false #false)

(require "forest/forest.scm")
(forest-configure! 'left #:ignore (list ".git" "target" "__pycache__" "node_modules"))
(forest-set-style! 'snacks)

(require "steel-pty/term.scm")
(set-default-shell! "/bin/zsh")

(require "helix-file-watcher/file-watcher.scm")
(spawn-watcher)

(require "streal/streal.scm")

(require "mattwparas-helix-package/cogs/recentf.scm")
(recentf-snapshot)
;; <<< helix-steel-plugins
