# ==================================
#            Languages.toml
# ==================================

# Rust
[[language]]
name = "rust"
language-servers = [ "rust-analyzer" ]
auto-format = true

[language.formatter]
command = "rustfmt"
args = ["--edition", "2021"]

# Go
[[language]]
name = "go"
auto-format = true
language-servers = [ "gopls" ]

# Python
[[language]]
name = "python"
language-servers = [ "pyright" ]
auto-format = true

[language.formatter]
command = "black"

# JavaScript / TypeScript
[[language]]
name = "javascript"
language-servers = [ "typescript-language-server" ]

[[language]]
name = "typescript"
language-servers = [ "typescript-language-server" ]

# HTML
[[language]]
name = "html"
language-servers = [ "vscode-html-languageserver" ]

# CSS
[[language]]
name = "css"
language-servers = [ "vscode-css-languageserver" ]

# # PHP
# [language-server.phpactor]
# command = "phpactor"
# args = ["language-server"]

[language-server.intelephense.config]
environment.phpVersion = "7.3.0"
environment.includePaths = ["vendor", "src", "config", "templates"]
files.associations = ["*.php", "*.ctp"]

[[language]]
name = "php"
file-types = ["php", "inc", "php4", "php5", "phtml", "ctp"]

# [[language]]
# name = "php"
# language-servers = [ "phpactor" ]
# roots = [".git", "composer.json", "index.php"]
